config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"

  resources :questions, except: %i[edit] do
    resources :answers, shallow: true, only: %i[show create update destroy] do
      resource :best, only: %i[create], module: :answers, controller: "best"
    end
  end

  resources :attachments, only: %i[destroy]
  resources :rewards, only: %i[index]
  resources :votes, only: %i[create]
  resources :comments, only: %i[create]

  mount ActionCable.server => "/cable"
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: "User"

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable

  has_one :reward, dependent: :destroy

  has_many_attached :files

  validates :title, :body, presence: true

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_question, only: %i[show update destroy]

  after_action :publish_question, only: %i[create]

  def index
    @questions = Question.order(created_at: :desc)
  end

  def show
    @answer = Answer.new
    @answer.links.build
    @answers = @question.answers.with_attached_files.sort_by_best
  end

  def new
    @question = Question.new
    @question.links.build
    @reward = Reward.new(question: @question)
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: "Your question successfully created."
    else
      render :new
    end
  end

  def update
    @question.update(question_params) if current_user.author_of?(@question)
  end

  def destroy
    @question.destroy if current_user.author_of?(@question)
  end

  private

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      files: [],
      links_attributes: %i[id name url _destroy],
      reward_attributes: %i[title image]
    )
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast("questions", { html: ApplicationController.render(
      partial: "questions/question",
      locals: { question: @question }
    ) })
  end
end

app/views/questions/_question.html.slim
.card.card-body.mb-3 id="question-#{question.id}"
  .d-flex.justify-content-between
    = link_to question.title, question

    - if local_assigns[:current_user]&.author_of?(question)
      div
        => link_to "Edit", "#", class: "edit-question-link", data: { question_id: question.id }
        = link_to "Delete", question, method: :delete, remote: true, data: { confirm: "Are you sure?" }

  = form_with model: question, local: false, class: "hidden", html: { id: "edit-question-#{question.id}" } do |f|
    .question-fields
      .my-3
        = f.label :title, "Title", class: "form-label"
        = f.text_field :title, class: "form-control"
      .mb-3
        = f.label :body, "Body", class: "form-label"
        = f.text_area :body, class: "form-control"
    .mb-3
      = f.label :files, class: "form-label"
      = f.file_field :files, multiple: true, direct_upload: true, class: "form-control"
    .my-4
      = f.fields_for :links do |l|
        = render "shared/link_fields", f: l
      p = link_to_add_association "Add one more link", f, :links, partial: "shared/link_fields"

    = f.submit "Save", class: "btn btn-success width-10"

app/views/questions/destroy.js.erb
document.getElementById("question-<%= @question.id %>")?.remove()

app/views/questions/index.html.slim
h1 Questions

.question-errors
  = render "shared/errors", resource: @question

p = link_to "Ask question", new_question_path

.questions
  = render @questions

app/views/questions/new.html.slim
= render "shared/errors", resource: @question

= form_with model: @question do |f|
  .card.card-body.mt-4
    .question-fields
      .mb-4
        = f.label :title, class: "form-label"
        = f.text_field :title, class: "form-control"
      .mb-4
        = f.label :body, class: "form-label"
        = f.text_area :body, class: "form-control"
    .mb-4
      = f.label :files, class: "form-label"
      = f.file_field :files, multiple: true, direct_upload: true, class: "form-control"
    .my-4
      = f.fields_for :links do |l|
        = render "shared/link_fields", f: l
      p = link_to_add_association "Add one more link", f, :links, partial: "shared/link_fields"
    .my-4
      p Reward:
      = f.fields_for :reward do |r|
        .reward-fields
          p
            = r.label :title, class: "form-label"
            = r.text_field :title, class: "form-control"
          p
            = r.label :image, class: "form-label"
            = r.file_field :image, direct_upload: true, class: "form-control"
    .mb-2
      = f.submit "Ask", class: "btn btn-success width-10"

app/views/questions/show.html.slim
.question.my-3 data-question-id=@question.id
  h3 = @question.title
  p = @question.body

  .mb-4.d-flex.justify-content-end.question-votes = render partial: "shared/rating", locals: { resource: @question }

  - if @question.reward.present?
    p Reward:
    = image_tag url_for(@question.reward.image), size: "36"
    = @question.reward.title

  - if @question.files.attached?
    - @question.files.each do |file|
      p id="file-#{file.id}"
        => link_to file.filename.to_s, url_for(file)

        - if current_user&.author_of?(@question)
          = link_to "Delete file", attachment_path(file), method: :delete, remote: true

  - if @question.links.any?
    .links
      p Links:
      ul
        - @question.links.each do |link|
          li
            = link_to ERB::Util.html_escape(link.name),
              ERB::Util.html_escape(link.url), target: "_blank", rel: "noopener noreferrer"
            - if link.gist?
              = javascript_include_tag "#{link.url}.js"

  div id="question-#{@question.id}-comments"
    p Comments:
    ul
      = render @question.comments
    - if user_signed_in?
      .mb-4
        = link_to "Add comment", "#", class: "add-comment-link"
        = render "comments/form", commentable: @question

  h4 Answers
  .answer-errors
    = render "shared/errors", resource: @answer

  .answers
    = render @answers

  h4 Answer a question
  = render "answers/form", answer: @answer

app/views/questions/update.js.erb
document.querySelector(".question-errors").innerHTML = '<%= render "shared/errors", resource: @question %>'

<% unless @question.errors.present? %>
  document.querySelector("#question-<%= @question.id %>").outerHTML = '<%= j render @question %>'
<% end %>