config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"

  resources :questions, except: %i[edit] do
    resources :answers, shallow: true, only: %i[show create update destroy] do
      resource :best, only: %i[create], module: :answers, controller: "best"
    end
  end

  resources :attachments, only: %i[destroy]
  resources :rewards, only: %i[index]
  resources :votes, only: %i[create]
  resources :comments, only: %i[create]

  mount ActionCable.server => "/cable"
end

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  .alert.alert-danger.alert-dismissible.fade.show role="alert"
    h4.alert-heading = "#{resource.errors.count} error(s) detected: "
    ul
      -resource.errors.full_messages.each do |message|
        li = message
    button.btn-close type="button" data-bs-dismiss="alert" aria-label="Close"

app/views/shared/_flash.html.slim
- flash.each do |type, msg|
  #alert class="alert #{bootstrap_class_for_flash(type)} alert-dismissible text-center rounded-0" role="alert"
    = msg
    button.btn-close type="button" data-bs-dismiss="alert" aria-label="Close"

app/views/shared/_link_fields.html.slim
.nested-fields
  .mb-3
    = f.label :name, "Link name", class: "form-label"
    = f.text_field :name, class: "form-control"
  .mb-3
    = f.label :url, class: "form-label"
    = f.text_field :url, class: "form-control"

  p = link_to_remove_association "Remove link", f

app/views/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    = link_to "Thinknetica QNA Project", root_path, class: "navbar-brand"
    button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon

    .collapse.navbar-collapse#navbarText
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        li
          = link_to "Home", root_path, class: "nav-item nav-link"

      ul.navbar-nav.mb-2.mb-lg-0
        - if user_signed_in?
          li = link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link"
          li = link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link"
          li = link_to "My rewards", rewards_path, class: "nav-item nav-link"
        - else
          li = link_to "Login", new_user_session_path, class: "nav-item nav-link"
          li = link_to "Sign up", new_user_registration_path, class: "nav-item nav-link"

app/views/shared/_rating.html.slim
.vote.d-flex.align-items-center[data-resource-id="#{resource.class.to_s.underscore}-#{resource.id}"]
  - votable_type = resource.class.to_s.underscore
  - votable_id = resource.id

  - if current_user && !current_user.author_of?(resource)
    = button_to votes_path,
      params: { value: 1,
                votable_type: votable_type,
                votable_id: votable_id },
      method: :post,
      remote: true,
      format: JSON,
      class: "vote-up btn btn-sm btn-outline-success"
      | &#128077;

  .rating.mx-3 = resource.rating

  - if current_user && !current_user.author_of?(resource)
    = button_to votes_path,
      params: { value: -1,
                votable_type: votable_type,
                votable_id: votable_id },
      method: :post,
      remote: true,
      format: JSON,
      class: "vote-down btn btn-sm btn-outline-secondary"
      | &#128078;