config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"

  resources :questions, except: %i[edit] do
    resources :answers, shallow: true, only: %i[show create update destroy] do
      resource :best, only: %i[create], module: :answers, controller: "best"
    end
  end

  resources :attachments, only: %i[destroy]
  resources :rewards, only: %i[index]
  resources :votes, only: %i[create]
  resources :comments, only: %i[create]

  mount ActionCable.server => "/cable"
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :author, class_name: "User"

  has_many :links, dependent: :destroy, as: :linkable

  has_one :reward, dependent: :nullify

  has_many_attached :files

  validates :body, presence: true

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  scope :sort_by_best, -> { order(best: :desc, created_at: :desc) }

  def mark_as_best
    transaction do
      question.answers.update_all(best: false)
      update(best: true)
      update(reward: question.reward) if question.reward
    end
  end
end

app/controllers/answers/best_controller.rb
# frozen_string_literal: true

module Answers
  class BestController < ApplicationController
    before_action :authenticate_user!

    def create
      answer = Answer.find(params[:answer_id])
      question = answer.question

      answer.mark_as_best if current_user.author_of?(question)
      @answers = question.answers.sort_by_best
    end
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: %i[show update destroy]

  after_action :publish_answer, only: %i[create]

  def show
    render partial: "answers/answer", locals: { answer: @answer, current_user: current_user }
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.author = current_user

    return unless @answer.save

    flash.now[:notice] = "Your answer successfully created."
  end

  def update
    @answer.update(answer_params)
    question = @answer.question
    @answers = question.answers.sort_by_best
  end

  def destroy
    return unless current_user.author_of?(@answer)

    @answer.destroy
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(
      :body,
      files: [],
      links_attributes: %i[id name url _destroy]
    )
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{@question.id}/answers",
      { user_id: current_user.id, question_id: @question.id, answer_id: @answer.id }
    )
  end
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .card.card-body.mb-3 id="answer-#{answer.id}"
    p = answer.body

    .mb-4.d-flex.justify-content-end = render partial: "shared/rating", locals: { resource: answer }

    - if answer.links.any?
      .links
        p Links:
        ul
          - answer.links.each do |link|
            li
              = link_to ERB::Util.html_escape(link.name),
                ERB::Util.html_escape(link.url), target: "_blank", rel: "noopener noreferrer"
              - if link.gist?
                = javascript_include_tag "#{link.url}.js"

    - if answer.files.attached?
      - answer.files.each do |file|
        p id="file-#{file.id}"
          => link_to file.filename.to_s, url_for(file)

          - if current_user&.author_of?(answer)
            = link_to "Delete file", attachment_path(file), method: :delete, remote: true

    - if answer.best
      p Best answer

    - if current_user&.author_of?(answer.question) && !answer.best
      p = link_to "Best", answer_best_path(answer), method: :post, remote: true

    - if current_user&.author_of?(answer)
      p
        => link_to "Edit", "#", class: "edit-answer-link", data: { answer_id: answer.id }
        = link_to "Delete", answer, method: :delete, remote: true, data: { confirm: "Are you sure?" }

    div id="answer-#{answer.id}-comments"
      p Comments:
      ul
        = render answer.comments
      - if user_signed_in?
        div
          = link_to "Add comment", "#", class: "add-comment-link"
          = render "comments/form", commentable: answer

    = form_with model: answer, local: false, class: "hidden", html: { id: "edit-answer-#{answer.id}" } do |f|
      .mb-3
        = f.label :body, "Your answer", class: "form-label"
        = f.text_area :body, class: "form-control"
      .mb-3
        = f.label :files, class: "form-label"
        = f.file_field :files, multiple: true, direct_upload: true, class: "form-control"
      .my-4
        = f.fields_for :links do |l|
          = render "shared/link_fields", f: l
        p = link_to_add_association "Add one more link", f, :links, partial: "shared/link_fields"

      = f.submit "Save", class: "btn btn-success width-10"

app/views/answers/_form.html.slim
= form_with model: [@question, answer], local: false do |f|
  .mb-4
    = f.label :body, class: "form-label"
    = f.text_area :body, class: "form-control new-answer-body"
  .mb-4
    = f.label :files, class: "form-label"
    = f.file_field :files, multiple: true, direct_upload: true, class: "form-control"
  .my-4
    = f.fields_for :links do |l|
      = render "shared/link_fields", f: l
    p = link_to_add_association "Add one more link", f, :links, partial: "shared/link_fields"

  = f.submit "Answer", class: "btn btn-success width-10"

app/views/answers/create.js.erb
document.querySelector(".answer-errors").innerHTML = '<%= render "shared/errors", resource: @answer %>'

<% if @answer.persisted? %>
  document.querySelector('.flash').innerHTML = '<%=  render "shared/flash" %>'
  document.querySelector(".answers").insertAdjacentHTML("beforeend", "<%= j render @answer %>")
  document.querySelector(".new-answer-body").value = ''
  document.querySelectorAll('.nested-fields').forEach(el => el.remove())
<% end %>

app/views/answers/destroy.js.erb
document.getElementById("answer-<%= @answer.id %>")?.remove()

app/views/answers/update.js.erb
document.querySelector(".answer-errors").innerHTML = '<%= render "shared/errors", resource: @answer %>'

<% unless @answer.errors.present? %>
  document.querySelector(".answers").innerHTML = '<%= j render @answers %>'
<% end %>